// Generated by gencpp from file beginner_tutorlials/AddTwoInts.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORLIALS_MESSAGE_ADDTWOINTS_H
#define BEGINNER_TUTORLIALS_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <beginner_tutorlials/AddTwoIntsRequest.h>
#include <beginner_tutorlials/AddTwoIntsResponse.h>


namespace beginner_tutorlials
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace beginner_tutorlials


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::beginner_tutorlials::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::beginner_tutorlials::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::beginner_tutorlials::AddTwoInts > {
  static const char* value()
  {
    return "beginner_tutorlials/AddTwoInts";
  }

  static const char* value(const ::beginner_tutorlials::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::beginner_tutorlials::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::beginner_tutorlials::AddTwoInts >
template<>
struct MD5Sum< ::beginner_tutorlials::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorlials::AddTwoInts >::value();
  }
  static const char* value(const ::beginner_tutorlials::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorlials::AddTwoIntsRequest> should match
// service_traits::DataType< ::beginner_tutorlials::AddTwoInts >
template<>
struct DataType< ::beginner_tutorlials::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorlials::AddTwoInts >::value();
  }
  static const char* value(const ::beginner_tutorlials::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::beginner_tutorlials::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::beginner_tutorlials::AddTwoInts >
template<>
struct MD5Sum< ::beginner_tutorlials::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorlials::AddTwoInts >::value();
  }
  static const char* value(const ::beginner_tutorlials::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorlials::AddTwoIntsResponse> should match
// service_traits::DataType< ::beginner_tutorlials::AddTwoInts >
template<>
struct DataType< ::beginner_tutorlials::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorlials::AddTwoInts >::value();
  }
  static const char* value(const ::beginner_tutorlials::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BEGINNER_TUTORLIALS_MESSAGE_ADDTWOINTS_H
